name: keycloak
version: 0.1.0
description: Keycloak Server
keywords:
  - Authentication
home: http://keycloak.org
sources:
  - https://keycloak.org
maintainers:
  - name: Marcel Beck
    email: marcel@beck.im

