
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "keycloak.fullname" . }}
  labels:
    app: {{ template "keycloak.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  postgresql-host: {{ template "keycloak.postgresql.fullname" . }}
  postgresql-database: {{ .Values.postgresql.postgresDatabase | quote }}
  postgresql-user: {{ .Values.postgresql.postgresUser | quote }}
  postgresql-password: {{ .Values.postgresql.postgresPassword | quote }}

  keycloak-loglevel: {{ default "INFO" .Values.keycloak.loglevel | quote }}
  keycloak-username: {{ default "keycloak" .Values.keycloak.username | quote }}
  keycloak-password: {{ default "keycloak" .Values.keycloak.password | quote }}
