apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "keycloak.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "keycloak.fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"
          - name: KEYCLOAK_LOGLEVEL
            valueFrom:
              configMapKeyRef:
                name: {{ template "keycloak.fullname" . }}
                key: keycloak-loglevel
          - name: KEYCLOAK_USER
            valueFrom:
              configMapKeyRef:
                name: {{ template "keycloak.fullname" . }}
                key: keycloak-username
          - name: KEYCLOAK_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: {{ template "keycloak.fullname" . }}
                key: keycloak-password

          - name: POSTGRES_PORT_5432_TCP_ADDR
            valueFrom:
              configMapKeyRef:
                name: {{ template "keycloak.fullname" . }}
                key: postgresql-host
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ template "keycloak.fullname" . }}
                key: postgresql-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "keycloak.postgresql.fullname" . }}
                key: postgres-password
          - name: POSTGRES_DATABASE
            valueFrom:
              configMapKeyRef:
                name: {{ template "keycloak.fullname" . }}
                key: postgresql-database
        ports:
        - containerPort: {{ .Values.keycloak.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.keycloak.service.internalPort }}
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.keycloak.service.internalPort }}
          initialDelaySeconds: 5
          timeoutSeconds: 1
