apiVersion: v1
kind: Service
metadata:
  name: {{ template "keycloak.fullname" . }}
{{- if .Values.keycloak.service.annotations }}
  annotations:
{{ toYaml .Values.keycloak.service.annotations | indent 4 }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
{{- if .Values.keycloak.service.labels }}
{{ toYaml .Values.keycloak.service.labels | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.keycloak.service.type }}
  ports:
  - port: {{ .Values.keycloak.service.externalPort }}
    targetPort: {{ .Values.keycloak.service.internalPort }}
    protocol: TCP
  selector:
    app: {{ template "keycloak.fullname" . }}
